### ISSUE TITLE
Where is the module common_types defined?

### ISSUE THREAD

**Issue by Beliavsky** [gzahl/tap#1]
The module common_types is USEd in tap.f90. Where is it defined? Thanks for the project.

**Comment by gzahl** [comment]
Hi, i think that module is not really needed. Does it compile without?
You can also compare this version: https://github.com/tillense/fosite/tree/master/common
That is the project i originally wrote this lib for. It does not use the common_types in that version anymore (instead it has some dependency for logging..)

**Comment by Beliavsky** [comment]
Thanks -- it's not needed, since the file can be compiled without it. I suggest removing that line from the file

**Comment by gzahl** [comment]
Done: https://github.com/gzahl/tap/pull/2
Thanks for the suggestion!
